
// This file has been generated by the GUI designer. Do not modify.
namespace DonationTracker.Desktop
{
	public partial class DonorAdditionWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry FirstNameTextBox;

		private global::Gtk.Entry LastNameTextBox;

		private global::Gtk.Entry AmountTextBox;

		private global::Gtk.Button DonorAdditionButton;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Button CancelButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DonationTracker.Desktop.DonorAdditionWindow
			this.Name = "DonationTracker.Desktop.DonorAdditionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Add Donor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DonationTracker.Desktop.DonorAdditionWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.FirstNameTextBox = new global::Gtk.Entry();
			this.FirstNameTextBox.CanFocus = true;
			this.FirstNameTextBox.Name = "FirstNameTextBox";
			this.FirstNameTextBox.IsEditable = true;
			this.FirstNameTextBox.InvisibleChar = '●';
			this.fixed1.Add(this.FirstNameTextBox);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.FirstNameTextBox]));
			w1.X = 125;
			w1.Y = 64;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.LastNameTextBox = new global::Gtk.Entry();
			this.LastNameTextBox.CanFocus = true;
			this.LastNameTextBox.Name = "LastNameTextBox";
			this.LastNameTextBox.IsEditable = true;
			this.LastNameTextBox.InvisibleChar = '●';
			this.fixed1.Add(this.LastNameTextBox);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.LastNameTextBox]));
			w2.X = 125;
			w2.Y = 125;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.AmountTextBox = new global::Gtk.Entry();
			this.AmountTextBox.CanFocus = true;
			this.AmountTextBox.Name = "AmountTextBox";
			this.AmountTextBox.IsEditable = true;
			this.AmountTextBox.InvisibleChar = '●';
			this.fixed1.Add(this.AmountTextBox);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.AmountTextBox]));
			w3.X = 125;
			w3.Y = 187;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.DonorAdditionButton = new global::Gtk.Button();
			this.DonorAdditionButton.WidthRequest = 150;
			this.DonorAdditionButton.CanFocus = true;
			this.DonorAdditionButton.Name = "DonorAdditionButton";
			this.DonorAdditionButton.UseUnderline = true;
			this.DonorAdditionButton.Label = global::Mono.Unix.Catalog.GetString("Add Donor");
			this.fixed1.Add(this.DonorAdditionButton);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.DonorAdditionButton]));
			w4.X = 200;
			w4.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("First Name:");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w5.X = 29;
			w5.Y = 71;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Last Name:");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w6.X = 29;
			w6.Y = 130;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Amount:");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w7.X = 29;
			w7.Y = 195;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CancelButton = new global::Gtk.Button();
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.fixed1.Add(this.CancelButton);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.CancelButton]));
			w8.X = 107;
			w8.Y = 240;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 432;
			this.DefaultHeight = 334;
			this.Show();
			this.DonorAdditionButton.Clicked += new global::System.EventHandler(this.AddDonor);
			this.CancelButton.Clicked += new global::System.EventHandler(this.Cancel);
		}
	}
}
